config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :cards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :sender
  mount_uploaders :gif, GifUploader
  serialize :gif, JSON
end

app/models/sender.rb
class Sender < ApplicationRecord
  has_many :cards
  accepts_nested_attributes_for :cards, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @sender = Sender.new
    @sender.cards.build
  end

  def create
    begin
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => 299,
        :description => 'christmasgifcards.com',
        :currency    => 'usd'
      )
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to action: :new_card
    end
    @sender = Sender.new(sender_params)
    if @sender.save
      flash[:notice] = 'Thank you for your order! Your card will be in the mail soon.'
      CardMailer.card_sent(@sender).deliver_later
      CardMailer.thank_you(@sender).deliver_later
    end
    redirect_to :new_card
  end

  private

  def sender_params
    params.require(:sender).permit(:name, :email, :address, :city, :state, :zip, cards_attributes: [:name, :address, :city, :state, :zip, :comment, {gif: []}])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/new.html.erb
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Christmas GIF Cards</span>
</nav>
<% if flash[:notice] %>
  <div class="alert alert-primary" role="alert">
    <p class='h3'><strong><%= flash[:notice] %></strong></p>
  </div>
<% end %>
<div class='container-fluid'>
  <h2>Your Information</h2>
  <%= form_with scope: @sender, url: cards_path, local: true do |sender| %>
    <div class='form-group'>
      <%= label_tag do %>
        Your Name
        <%= sender.text_field :name, class: 'form-control' %>
      <% end %>
    </div>
    <div class='form-group'>
      <%= label_tag do %>
        Your Email
        <%= sender.text_field :email, class: 'form-control' %>
      <% end %>
    </div>
    <div class='form-group'>
      <%= label_tag do %>
        Your Address
        <%= sender.text_field :address, class: 'form-control' %>
      <% end %>
    </div>
    <div class='form-group'>
      <%= label_tag do %>
        Your City
        <%= sender.text_field :city, class: 'form-control' %>
      <% end %>
    </div>
    <div class='form-group'>
      <%= label_tag do %>
        Your State
        <%= sender.select :state, options_for_select(us_states), class: 'form-control' %>
      <% end %>
    </div>
    <div class='form-group'>
      <%= label_tag do %>
        Your Zip
        <%= sender.text_field :zip, class: 'form-control' %>
      <% end %>
    </div>
    <h2>Their Information</h2>
    <%= sender.fields_for :cards do |card| %>
      <div class='form-group'>
        <%= label_tag do %>
          Their Name
          <%= card.text_field :name, class: 'form-control' %>
        <% end %>
      </div>
      <div class='form-group'>
        <%= label_tag do %>
          Their Address
          <%= card.text_field :address, class: 'form-control' %>
        <% end %>
      </div>
      <div class='form-group'>
        <%= label_tag do %>
          Their City
          <%= card.text_field :city, class: 'form-control' %>
        <% end %>
      </div>
      <div class='form-group'>
        <%= label_tag do %>
          Their State
          <%= card.select :state, options_for_select(us_states), class: 'form-control' %>
        <% end %>
      </div>
      <div class='form-group'>
        <%= label_tag do %>
          Their Zip
          <%= card.text_field :zip, class: 'form-control' %>
        <% end %>
      </div>
      <h2>Comment and Gif</h2>
      <div class='form-group'>
        <%= label_tag do %>
          Comment (220 maximum characters)
          <%= card.text_area :comment, class: 'form-control', maxlength: 220 %>
        <% end %>
      </div>
      <div class='form-group'>
        <%= label_tag do %>
          GIF
          <%= card.file_field :gif, multiple: true %>
        <% end %>
      </div>
    <% end %>
    <script src="https://checkout.stripe.com/checkout.js"
          class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="ChristmasGIFCards.com"
          data-locale="auto"
          data-label="Send Card"></script>
  <% end %>
</div>

app/views/home/index.html.erb
<!-- Page Wrapper -->
<div id="page-wrapper">
  <!-- Header -->
  <header id="header" class="alt">
    <h1><a href="index.html">Christmas GIF Cards</a></h1>
  </header>
  <!-- Banner -->
  <section id="banner">
    <div class="inner">
      <h2>Christmas Gif Cards</h2>
      <p>Send a Christmas card with a gif<br />
      to Friends and family<br />
      without having having to leave your house.</p>
      <ul class="actions">
        <li><a href="/cards/new" class="button special">Send a card now for $2.99</a></li>
      </ul>
    </div>
    <a href="#one" class="more scrolly">Learn More</a>
  </section>
  <!-- One -->
  <section id="one" class="wrapper style1 special">
    <div class="inner">
      <header class="major">
        <h2>Send a physical Christmas card to anybody</h2>
        <p>You can send the card with a custom message and include a QR code to a gif with the card.<br />
        </p>
      </header>
      <%= image_tag 'santa_claus.gif' %>
    </div>
  </section>
  <!-- Two -->
  <section id="two" class="wrapper alt style2">
    <section class="spotlight">
      <div class="image"><%= image_tag "pic01.jpg" %></div>
      <div class="content">
        <h2>Gif</h2>
        <p>Submit a gif with your card and we will include a QR code for the card recipient to view the gift you submitted.</p>
      </div>
    </section>
    <section class="spotlight">
      <div class="image"><%= image_tag "pic02.jpg" %></div>
      <div class="content">
        <h2>Custom Message</h2>
        <p>You can include a message, up to 220 characters, to go with the card.</p>
      </div>
    </section>
    <section class="spotlight">
      <div class="image"><%= image_tag "pic03.jpg" %></div>
      <div class="content">
        <h2>We take care of the rest!</h2>
        <p>We will put together the card and mail it. You can cross something off your Holiday to-do list.</p>
      </div>
    </section>
  </section>
  <!-- CTA -->
  <section id="cta" class="wrapper style4">
    <div class="inner">
      <header>
        <h2>Send a Card Now!</h2>
        <p>Only takes a few minutes. Send card before 10 PM to guarantee card is in tomorrow's mail.</p>
      </header>
      <ul class="actions vertical">
        <li><a href="/cards/new" class="button fit special">Send Card</a></li>
      </ul>
    </div>
  </section>
  <!-- Footer -->
  <footer id="footer">
    <%= image_tag 'merry_christmas.gif' %><br>
    Special thanks to <a href='https://unsplash.com/@lesanderson'>Les Anderson</a>, <a href='https://unsplash.com/@anniespratt'>Annie Spratt</a>, <a href='https://unsplash.com/@arunkuchibhotla'>Arun Kuchibhotla</a>, and <a href='https://unsplash.com/@mikearney'>Mike Arney</a> for pictures.<br />
    Contact <%= mail_to "caleb@christmasgifcards.com" %> for help, questions, comments, etc.
    <ul class="copyright">
      <li>&copy; 2017 Christmas Gif Cards</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
    </ul>
  </footer>
</div>

<!-- Scripts -->
<%= javascript_include_tag 'jquery.min' %>
<%= javascript_include_tag 'jquery.scrollex.min' %>
<%= javascript_include_tag 'jquery.scrolly.min' %>
<%= javascript_include_tag 'skel.min' %>
<%= javascript_include_tag 'util' %>
<!--[if lte IE 8]><%= javascript_include_tag 'ie/respond.min' %><![endif]-->
<%= javascript_include_tag 'main' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Christmas Cards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109856159-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-109856159-1');
    </script>
  </head>

  <body class='landing'>
    <%= yield %>
  </body>
</html>